server:
  hide_html_extension: true
  domain: "http://localhost:8629"

content:
  title: "CESTMADDY"
  language: fr
  header_file: "./source/header.md"
  footer_file: "./source/footer.md"
  theme: "clean"
  favicon: {
    path: "./source/imgs/monogram_color.svg",
    background: "#fff",
    theme_color: "#8e443d"
  }