version: "3.9"
services:
  cestmaddy:
    image: "cestoliv/cestmaddy:v0.1.1"
    command: sh -c "ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone && npm run start-favicons"
    ports:
      - "${PORT}:80"
    volumes:
      # Website
      - ./config.yml:/cestmaddy/config.yml
      - ./source/:/cestmaddy/source
      - ./custom/:/cestmaddy/custom
